# see https://prometheus.io/docs/operating/configuration/
global:
  scrape_interval: 15s    # Default is 1m.
  scrape_timeout: 10s     # Default is 10s.
  evaluation_interval: 1m # Default is 1m.

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets:
          - localhost:9093

rule_files:
  - '*-rules.yml'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: 
        - localhost:9090
  - job_name: 'pce'
    scheme: https
    tls_config:
      ca_file: tls/prometheus-example-ca-crt.pem
      cert_file: tls/prometheus.example.com-client-crt.pem
      key_file: tls/prometheus.example.com-client-key.pem
    metrics_path: /pce/metrics
    static_configs:
      - targets:
        - prometheus.example.com:9009
  - job_name: 'pse'
    scheme: https
    tls_config:
      ca_file: tls/prometheus-example-ca-crt.pem
      cert_file: tls/prometheus.example.com-client-crt.pem
      key_file: tls/prometheus.example.com-client-key.pem
    metrics_path: /pse/metrics
    static_configs:
      - targets:
        - prometheus.example.com:9009
  - job_name: 'wmi'
    scheme: https
    tls_config:
      ca_file: tls/prometheus-example-ca-crt.pem
      cert_file: tls/prometheus.example.com-client-crt.pem
      key_file: tls/prometheus.example.com-client-key.pem
    metrics_path: /wmi/metrics
    static_configs:
      - targets:
        - prometheus.example.com:9009
  - job_name: 'blackbox-http'
    scheme: https
    tls_config:
      ca_file: tls/prometheus-example-ca-crt.pem
      cert_file: tls/prometheus.example.com-client-crt.pem
      key_file: tls/prometheus.example.com-client-key.pem
    metrics_path: /blackbox/probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://ruilopes.com
        - https://ruilopes.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus.example.com:9009
  - job_name: 'blackbox-ssh'
    scheme: https
    tls_config:
      ca_file: tls/prometheus-example-ca-crt.pem
      cert_file: tls/prometheus.example.com-client-crt.pem
      key_file: tls/prometheus.example.com-client-key.pem
    metrics_path: /blackbox/probe
    params:
      module: [ssh_banner]
    static_configs:
      - targets:
        - prometheus.example.com:22
        - ruilopes.com:22
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus.example.com:9009
